filebeat.inputs:
  - type: filestream
    id: external-app
    enabled: true
    paths:
      - "${LOG_PATH:/var/log/app/*.log}"
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          overwrite_keys: true

processors:
  - add_fields:
      target: ""
      fields:
        service: "${SERVICE_NAME:payment-api}"
        environment: "${ENVIRONMENT:prod}"

output.kafka:
  hosts: ["${KAFKA_BROKERS:my-cluster-kafka-bootstrap.kafka-dung.svc:9092}"]
  topic: "${KAFKA_TOPIC:vm-logs-topic}"
  codec.json:
    pretty: false

