# Github config file:  https://github.com/jertel/elastalert2/blob/master/chart/elastalert2/templates/deployment.yaml

apiVersion: apps/v1                 # Phiên bản API của Kubernetes cho tài nguyên Deployment
kind: Deployment                   # Loại tài nguyên: Deployment (quản lý việc triển khai Pod)
metadata:
  name: elastalert2                # Tên định danh của Deployment
  namespace: elk-dung              # Không gian tên (namespace) triển khai
spec:
  replicas: 1                      # Số lượng Pod ElastAlert chạy song song (mặc định 1)
  selector:
    matchLabels:
      app: elastalert2             # Nhãn nhận diện để quản lý các Pod
  template:
    metadata:
      labels:
        app: elastalert2           # Nhãn gán cho Pod khi được tạo ra
    spec:
      nodeSelector:                # Chọn Node cụ thể để chạy Pod
        kubernetes.io/hostname: wk03 # Chỉ chạy trên Node wk03
      containers:
      - name: elastalert2          # Tên Container bên trong Pod
        image: jertel/elastalert2:2.21.0 # Image Docker chính thức của ElastAlert2 (phiên bản 2.21.0)
        args:                      # Các tham số dòng lệnh khi khởi chạy
          - "--config"
          - "/opt/elastalert/config.yaml" # Chỉ định file cấu hình chính
          - "--verbose"            # Bật chế độ log chi tiết để dễ debug
        resources:                 # Giới hạn tài nguyên CPU/RAM cho Container
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"

        volumeMounts:              # Gắn (mount) các ổ đĩa vào Container
        - name: config
          mountPath: /opt/elastalert/config.yaml # Gắn file config từ ConfigMap
          subPath: config.yaml
        - name: rules
          mountPath: /opt/elastalert/rules # Gắn thư mục chứa các quy tắc cảnh báo (Rules)
      volumes:                     # Khai báo các nguồn dữ liệu (Volume)
      - name: config
        configMap:
          name: elastalert-config  # Lấy dữ liệu từ ConfigMap elastalert-config
      - name: rules
        configMap:
          name: elastalert-rules   # Lấy dữ liệu từ ConfigMap elastalert-rules
