# https://github.com/elastic/helm-charts/blob/main/kibana/values.yaml
elasticsearchHosts: "https://elasticsearch-master:9200"

kibanaConfig:
  kibana.yml: |
    elasticsearch.ssl.verificationMode: none

service:
  port: 5601

replicas: 1
