# Cấu hình Kibana Logging - High Availability (HA)
# File này dùng để chạy lệnh: helm upgrade kibana-dung elastic/kibana -f kibana-logging-values.yaml --namespace elk

elasticsearchHosts: "https://elasticsearch-master:9200"

kibanaConfig:
  kibana.yml: |
    elasticsearch.ssl.verificationMode: none

service:
  port: 5601

# Thiết lập HA: 3 bản sao rải đều trên 3 Node
replicas: 3
antiAffinity: "hard" 

