input {
  file {
    path => "${LOG_PATH:/var/log/app/*.log}"
    start_position => "beginning"
    sincedb_path => "/var/lib/logstash/sincedb-external-app"
    codec => json {
      ecs_compatibility => disabled
    }
  }
}

filter {
  mutate {
    add_field => {
      "service" => "${SERVICE_NAME:payment-api}"
      "environment" => "${ENVIRONMENT:prod}"
    }
  }
}

output {
  kafka {
    bootstrap_servers => "${KAFKA_BROKERS:my-cluster-kafka-bootstrap.kafka-dung.svc:9092}"
    topic_id => "${KAFKA_TOPIC:vm-logs-topic}"
    codec => json
  }
}

