# helm chart:  https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml
replicas: 1

# Cho Helm chờ ES đạt trạng thái yellow tối đa 1 giây.
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

# Cấp RAM heap JVM cho Elasticsearch: tối thiểu/tối đa 1536MB.
esJavaOpts: "-Xms1536m -Xmx1536m"

nodeSelector:
  kubernetes.io/hostname: wk03

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "3Gi"

volumeClaimTemplate:
  # Chỉ cho một node/pod mount ổ tại một thời điểm.
  accessModes: ["ReadWriteOnce"]
  # Chọn SC để cấp ổ
  storageClassName: "csi-cinder-sc-delete"
  resources:
    requests:
      storage: 10Gi

# Ghi thêm cấu hình vào file elasticsearch.yml trong pod.
esConfig:
  elasticsearch.yml: |
    # Bật xác thực user/password cho Elasticsearch.
    xpack.security.enabled: true
    # Bật HTTPS cho API Elasticsearch.
    xpack.security.http.ssl.enabled: true
    # Tắt Machine Learning để tiết kiệm tài nguyên.
    xpack.ml.enabled: false
    # Tắt tự tải GeoIP database.
    ingest.geoip.downloader.enabled: false

